species_config = {
    0: {"name": "rabbit", 
        "color" : "white", 
        "e": 75, "movement": 1, 
        "metabolism": 65, 
        "hunger_rate": 4,
        "eat_range": 0,
        "sense_range": 2,
        "sense_chance": 45,
        "litter": [2, 3, 4, 5, 6], 
        "prey": [-1]},
    1: {"name": "fox", 
        "color": "red",
        "e": 50, 
        "movement": 3, 
        "metabolism": 90, 
        "hunger_rate": 6,
        "eat_range": 2,
        "sense_range": 4,
        "sense_chance": 90,
        "litter": [1, 2], 
        "prey": [0]},
    2: {"name": "wolf", 
        "color": "blue",
        "e": 50, 
        "movement": 2, 
        "metabolism": 80, 
        "hunger_rate": 13,
        "eat_range": 3,
        "sense_range": 3,
        "sense_chance": 75,
        "litter": [2, 3], 
        "prey": [0, 1]},
}